name: Push files to Google Cloud Storage
on:
  push:
    branches:
      - CPDE-2864

jobs:
  upload-to-bucket:
    name: Upload files to bucket
    runs-on: [self-hosted, common]
    container:
      image: europe-docker.pkg.dev/ftcs-production/infrastructure/node-build-tools:20
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - name: "Echo in file"
      run: echo "Test"

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.THEME_SERVICE_ACCOUNT }}

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: '*'
        destination: 'theme.intergiro.com'

