name: Push files to Google Cloud Storage
on:
  push:
    branches:
      - CPDE-2864

jobs:
  upload-to-bucket:
    name: Upload files to bucket
    runs-on: [self-hosted, common]

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.THEME_SERVICE_ACCOUNT }}

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: '*'
        destination: 'theme.intergiro.com'

